config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  mount Attachinary::Engine => "/attachinary"

  get "/about", to: "pages#about"
  resources "contacts", only: [:new, :create]

  devise_for :users
  root "posts#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,    :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact from Latitudes",
      :to => "isabel.lamers@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, :abstract, :content, presence: true
  has_attachments :photos, maximum: 5
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :instagram_feed

private

  def instagram_feed
    @popular_images ||= Instagram.user_recent_media.sample(3)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_post

  def index
    @comments = @post.comments.all
  end

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)

    if @comment.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
     params.require(:comment).permit(:name, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  protect_from_forgery except: [:new, :create]

  skip_before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request

    respond_to do |format|
      if @contact.deliver
        format.html { redirect_to root_path, notice: "That better not be spam! No, seriously, I'm looking forward to read you." }
      else
        format.html { redirect_to root_path, warning: "Oops. Something went wrong. Just write me an email, 'kay? hello@anays.com" }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
    @sample_post = Post.all.sample if Post.any?

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_path @post , notice: 'Post was created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path @post, notice: 'Post was updated.'}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path
  end

private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :abstract, :content, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    Admin.first.user == current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def background_photo_url(post)
    if !post.photos.empty?
      "http://res.cloudinary.com/anays/image/upload/c_fit/#{post.photos.first.path}"
    else
      "http://res.cloudinary.com/anays/image/upload/c_fit/v1476000625/mi2flrts3h5jhshad8yb.jpg"
    end
  end
end

app/views/comments/_comment.html.erb
<p><b><%= comment.name %></b> said:</p>

<p><%= comment.body %></p>

<p><i><small><%= time_ago_in_words(comment.created_at)%> ago</small></i></p>

<%= link_to 'delete', [comment.post, comment], method: :delete, class: 'btn btn-primary', data: { confirm: 'Are you sure?' } if admin? %>
<br>
<br>

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build])  do |f| %>

<%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name  %>
    <%= f.input :body, as: :text, :input_html => { :rows => 5 } %>
   </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/_new.html.erb
<div class = "modal-dialog">
  <div class = "modal-content">
    <div class = "modal-header">
      <button aria-hidden = "true", class = "true", data-dismiss = "modal", type="button">x</button>
      <h1>Contact</h1>
      <div class = "modal-body">
        <%= simple_form_for @contact, remote: true, html: {class: "form-horizontal"} do |f| %>
          <%= f.input :name, :required => true %>
          <%= f.input :email, :required => true %>
          <%= f.input :message, :as => :text, :required => true, input_html: {rows: 10}%>
          <div class= "hidden">
            <%= f.input :nickname, :hint => 'Leave this field blank!' %>
          </div>
          <div>
            </br>
            <%= f.button :submit, 'Send message', :class=> "btn btn-style" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/create.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button aria-hidden = "true", class = "true", data-dismiss = "modal", type = "button">x</button>
      <h1>Don't dare spam me.</h1>
      <p>I'm reading you're message write now and it better be important. Just kidding ... Thanks for getting in touch!</p>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class = "modal-dialog top-padding-1">
  <div class = "modal-content">
    <div class = "modal-header">
      <a href="/" class="btn btn-default centered" role="button">x</a>
      <h2 class= "modal-title">Contact</h1>
      <div class = "modal-body">
        <%= simple_form_for @contact, html: {class: "form-horizontal"} do |f| %>
          <%= f.input :name, :required => true %>
          <%= f.input :email, :required => true %>
          <%= f.input :message, :as => :text, :required => true, input_html: {rows: 10}%>
          <div class= "hidden">
            <%= f.input :nickname, :hint => 'Leave this field blank!' %>
          </div>
          <div>
            </br>
            <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
  document.body.style.backgroundColor = "rgba(34,34,34,0.7)";
</script>

app/views/layouts/_cdn_links.html.erb
<link rel="stylesheet" type="text/css" href="
https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.8.6/jquery.fullPage.css" />
<link href="https://fonts.googleapis.com/css?family=Great+Vibes|Indie+Flower|Cormorant+Garamond|Raleway" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= csrf_meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= render 'layouts/cdn_links' %>

  <title><%= yield(:title) || "Latitudes" %></title>
  <meta name="description" content="<%= (yield(:description) || "").squish %>">

  <%= render 'layouts/rails_default' %>

</head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>
    <%= render 'shared/about_modal' %>

    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post  do |f| %>

<%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title  %>
    <%= f.input :abstract, as: :text, :input_html => { :rows => 3 } %>
    <%= f.input :content, :input_html => { :rows => 10 }%>
  </div>

  <%= f.input :photos, as: :attachinary %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/_fullpage_script.html.erb
<script type="text/javascript">
$(document).ready(function() {
    $('#fullpage').fullpage({

        //Navigation
        menu: '#menu',
        lockAnchors: false,
        anchors:['firstPage', 'secondPage'],
        navigation: false,
        navigationPosition: 'right',
        navigationTooltips: ['firstSlide', 'secondSlide'],
        showActiveTooltip: false,
        slidesNavigation: true,
        slidesNavPosition: 'bottom',

        //Scrolling
        css3: true,
        scrollingSpeed: 700,
        fitToSection: true,
        fitToSectionDelay: 1000,
        scrollBar: false,
        easing: 'easeInOutCubic',
        easingcss3: 'ease',
        loopBottom: false,
        loopTop: false,
        loopHorizontal: true,
        continuousVertical: false,
        continuousHorizontal: false,
        scrollHorizontally: false,
        interlockedSlides: false,
        resetSliders: false,
        fadingEffect: false,
        normalScrollElements: '#element1, .element2',
        scrollOverflow: false,
        scrollOverflowOptions: null,
        touchSensitivity: 15,
        normalScrollElementTouchThreshold: 5,
        bigSectionsDestination: null,

        //Accessibility
        keyboardScrolling: true,
        animateAnchor: true,
        recordHistory: true,

        //Design
        controlArrows: true,
        verticalCentered: true,
        sectionsColor : ['#ccc', '#fff'],
        paddingTop: '3em',
        paddingBottom: '10px',
        fixedElements: '#header, .footer',
        responsiveWidth: 0,
        responsiveHeight: 0,
        responsiveSlides: false,

        //Custom selectors
        sectionSelector: '.section',
        slideSelector: '.slide',

        //events
        onLeave: function(index, nextIndex, direction){},
        afterLoad: function(anchorLink, index){},
        afterRender: function(){},
        afterResize: function(){},
        afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){},
        onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex){}
    });
});
</script>

app/views/posts/_home_page.html.erb
<div class="section active" id="section1337">
  <div class="container">

    <div class="row">

      <div class="col-md-12">
        <h3 class="post_title">Chasing latitudes</h3>
        <small>
          <p>
            A blog by Anna Isabel Lamers
          </p>
        </small>
      </div>

    </div>

    <div class="row">
      <%= link_to "Check out: '#{@sample_post.title}'", @sample_post, class: "btn btn-primary outline" %>
    </div>

    <div class="row" id="home_arrow">
      <a href="/#secondPage"><i class="fa fa-arrow-down fa-2x white" aria-hidden="true"></i></a>
    </div>

  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
      <h1>Edit Post: <%= @post.title %></h1>

      <%= render 'form' %>

      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>
<%=  %>

app/views/posts/index.html.erb
<%= render 'fullpage_script' %>
<div id="fullpage">
  <%= render 'home_page' %>
  <% @posts.each do |post| %>
      <div class="section" id="section<%= post.id %>" style="background-image: url(<%= background_photo_url(post) %>)">
      <h3 class="post_title"><%= link_to post.title, post_path(post) %></h3>
      <p class="post_abstract"><%= post.abstract %></p>
      <p class="post_date"><%= post.created_at.strftime("%B %e, %Y") %></p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2">
      <h1>Add Blog Post</h1>

      <%= render 'form' %>

      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>
<%=  %>

app/views/posts/show.html.erb
<div class="container margin-top-60">
  <% if admin? %>
    <%= link_to 'Blogposts', posts_path %> |
    <%= link_to 'edit blogpost', edit_post_path(@post) %> |
    <%= link_to 'delete blogpost', @post, method: :delete, data: { confirm: 'Do you really want to delete this post?' } %>
  <% end %>
  <br>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-md-6">
      <h1 class= "text-center" id="post-title"><%= @post.title %></h1>
      <p class="text-center"><small>written by Anna Isabel Lamers on <%= @post.created_at.strftime("%B %e, %Y") %></small></p>
    </div>
    <div class="col-md-6" id="post-abstract">
      <p>"<%= @post.abstract %>"</p>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <div class="row">
    <div class="col-md-12" id="post-content">
      <p><%= @post.content %></p>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div id="owl-demo">
      <% @post.photos.each do |photo| %>
        <div class="item"><%= cl_image_tag photo.path, crop: :fit %></div>
      <% end %>
      </div>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <p>comments (<%= @post.comments.count %>)</p>
      <%= render @post.comments %>
      <hr>
    </div>
    <div class="col-md-4">
      <% if current_user %>
        <h4>Add a comment:</h4>
        <%= render 'comments/form', locals: { object: @post} %>
      <% else %>
        <p><%= link_to t(".sign_in", default: "Login to comment"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></p>
      <% end %>
    </div>
  </div>
  <br>

  <% if admin? %>
    <%= link_to 'edit post', edit_post_path(@post) %> |
    <%= link_to 'delete post', @post, method: :delete, data: { confirm: 'Do you really want to delete this post?' } %>
  <% end %>
  <%= link_to :back, id: "home_arrow" do %>
    <i class="fa fa-arrow-left fa-3" aria-hidden="true"></i>
  <% end %>
</div>

app/views/shared/_about_modal.html.erb
<div class="modal modal-fullscreen fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-body">
          <div class="row">
            <div class="about-intro col-md-4 col-md-offset-1">
              <p class="white">
              <br>
              <br>
                "As a bi-national, multi-lingual, pluri-professional citizen of the world, I have learned to appreciate that every place, society, country and community has their ups and downs, their pro and cons. Being a searching soul, I share my observations from the places I have lived in and am happy to connect, share and learn!"
              </p>
              <hr>
              <div class="row">
                <div class="col-md-6">
                  <%= link_to "https://crimpr.herokuapp.com" do %>
                    <%= image_tag("Crimpr_LogoStudyTwo.png", height: "100", width: "170", alt: "https://crimpr.herokuapp.com") %>
                  <% end %>
                </div>
                <div class="col-md-6">
                  <p class="white italic thin">
                    Crimpr is a crowdsource-based web application to find the nearest climbing spots around you.
                  </p>
                </div>
              </div>
            </div>
            <div class="col-md-5 col-md-offset-1 text-center">
            <br>
              <%= image_tag('profile_pic.jpg', height: "320", width: "426") %>
            </div>
          </div>
          <hr>
          <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <%= render 'shared/instagram_feed', locals: {popular_images: @popular_images}%>
          </div>
          </div>
        </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-md-12 col-md-offset-4">
            <%= render 'shared/social_media' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_instagram_feed.html.erb
<% @popular_images.each do |popular| %>
  <div class="col-sm-12 col-md-4">
    <div class="thumbnail" style="margin-top: 22px;">
      <%= link_to "https://www.instagram.com/ana.yz/" do %>
        <%= image_tag popular.images.thumbnail.url %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_instagram_widget.html.erb
<!-- LightWidget WIDGET --><script src="//lightwidget.com/widgets/lightwidget.js"></script><iframe src="//lightwidget.com/widgets/ab705cbad48b5ce2856d3510d4fae65e.html" id="lightwidget_ab705cbad4" name="lightwidget_ab705cbad4" scrolling="no" allowtransparency="true" class="lightwidget-widget" style="width: 100%; border: 0; overflow: hidden;"></iframe>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse transparent">
  <div class="container">
    <%= link_to "Latitudes", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", "#myModal", :class => "btn", "data-toggle" => "modal" %></li>
        <li><%= link_to "Contact",  new_contact_path %></li>
        <% if user_signed_in? %>
          <% if admin? %>
            <li>
              <%= link_to new_post_path do %>
                <i class="fa fa-pencil-square-o"></i>  <%= t ".new_post", default: "Post" %>
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="fa fa-pencil-square-o"></i> <%= t ".edit_profile", default: "Edit Profile" %>
                  <% end %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Sign out" %>
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete unless admin? %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_social_media.html.erb
<ul id="social-list">
  <li class="social-item">
    <a href="https://www.facebook.com/htjlamers">
      <i class="fa fa-facebook fa-2x"></i>
    </a>
  </li>
  <li class="social-item">
    <a href="https://be.linkedin.com/in/isabellamers">
      <i class="fa fa-linkedin fa-2x"></i>
    </a>
  </li>
  <li class="social-item">
    <a href="https://twitter.com/_AnaYs_">
      <i class="fa fa-twitter fa-2x"></i>
    </a>
  </li>
  <li class="social-item">
    <a href="https://www.instagram.com/ana.yz/">
      <i class="fa fa-instagram fa-2x"></i>
    </a>
  </li>
  <li class="social-item">
    <a href="https://github.com/AnaYs/">
      <i class="fa fa-github fa-2x"></i>
    </a>
  </li>
</ul>